"""empty message

Revision ID: a32b55f68c61
Revises: c4e045b56388
Create Date: 2022-11-06 16:22:18.307221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a32b55f68c61'
down_revision = 'c4e045b56388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('add_date', sa.DateTime(), nullable=False))
    op.add_column('category', sa.Column('pub_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'pub_date')
    op.drop_column('category', 'add_date')
    # ### end Alembic commands ###
